project:
  type: website

website:
  title: "🧠 Hellen and LLMs"
  favicon: favicon.ico

  navbar:
    background: "#f8f9fa"
    right:
      - text: "About"
        href: about.qmd
      - text: "Posts"
        href: index.qmd
      - text: "GitHub"
        icon: github
        href: https://github.com/hellenjin13
      - text: "Twitter"
        icon: twitter
        href: https://twitter.com
          
  page-footer:
    left: "© 2025 Hellen Jin"
    center: "Built with Quarto • Updated {{< meta date >}}"
    right:
      - icon: envelope
        text: "heljin13@sas.upenn.edu"
        href: mailto:heljin13@sas.upenn.edu

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    code-copy: true

execute:
  freeze: auto
